// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TxToVdkYJCjm-6vFyhPSuRjhumF3tr4',
    appId: '1:984228719401:android:e0b31aea86a54459106538',
    messagingSenderId: '984228719401',
    projectId: 'paulineife',
    storageBucket: 'paulineife.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASMZXy8v3SoRRSuKSoZN9AcUH2T9tKJn0',
    appId: '1:984228719401:ios:9cdb0319c34d0c2a106538',
    messagingSenderId: '984228719401',
    projectId: 'paulineife',
    storageBucket: 'paulineife.appspot.com',
    androidClientId: '984228719401-dh8alugoqagld6vfnq6m14sfllibp6na.apps.googleusercontent.com',
    iosClientId: '984228719401-aodhlbojsc2njnfqut1ior4plv44biik.apps.googleusercontent.com',
    iosBundleId: 'org.microprogramers.paulineifeUser',
  );
}
